EdBPrepareCarefully.csproj
EdBPrepareCarefully.sln
Properties/AssemblyInfo.cs
Resources/About/About.xml

Updated version number to 0.14.0.1 to better reflect beta status

Updated version number

---

EdBPrepareCarefully.csproj
EdBPrepareCarefully.sln
Properties/AssemblyInfo.cs
Resources/About/About.xml

Updated version number to 0.14.0.2 in preparation for second beta release.

Updated version number of beta 2 release

---

EdBPrepareCarefully.csproj
EdBPrepareCarefully.sln
Properties/AssemblyInfo.cs
Resources/About/About.xml

Updated the "target" version of the mod to `0.14.1238` and the mod version to `0.14.0.3`

Updated target version to 1238 and 0.14.0.3

---

EdBPrepareCarefully.csproj
EdBPrepareCarefully.sln
Properties/AssemblyInfo.cs
Resources/About/About.xml

Incremented version numbers for bug fix release.

Updated version to 0.14.0.4

---

Source/CostCalculator.cs

Changes to better address issue #18.  Adding better validation, error handling and logging when trying to compute the cost of items during equipment database generation.

Issue #18: Added better error handling during cost calculation

---

Source/Page_ConfigureStartingPawnsCarefully.cs

Sort the apparel and hair lists by label so that they are more manageable when dealing with lots of mods.

Sort the apparel and hair lists by label

---

Source/EquipmentDatabase.cs
Source/Page_Equipment.cs

- Fixed the rendering of the animals tab to draw colors properly.  Issue #40.
- Fixed the rendering of furniture to be sized properly.

Fix for animal and furniture rendering on the equipment page

---

Resources/Languages/English/Keyed/EdBPrepareCarefully.xml
Source/Configuration.cs
Source/CostCalculator.cs
Source/CustomPawn.cs
Source/Page_Equipment.cs
Source/Page_PrepareCarefully.cs
Source/PrepareCarefully.cs

- Added point system back in.
- Removed fixed points.
- Fixed problem where pawn skills were not being reset properly after changes.

Added point system back in

---

Source/InjuryManager.cs
Source/Page_ConfigureStartingPawnsCarefully.cs

Added fixes to sort hair definitions and injury options correctly.

Fixes for unsorted hair definitions and injuries options

---

EdBPrepareCarefully.csproj
README.md

Removed some artifacts of old, removed settings from the project file.  This should fix some issues when trying to open it in Visual Studio.

Cleaned up the project file

---

README.md
dist.bat

Added a Windows batch script that automatically packaging the mod resources and a built release DLL into a complete mod directory.

Add a dist script to automatically package the mod

---

Source/PawnColorUtils.cs

Updated PawnColorUtils with an indirect method for determining the collors from PawnSkinColors.  This approach may work better with mods that have detours methods in the PawnSkinColors class.

Indirect approach to determine pawn colors

---

EdBPrepareCarefully.csproj
Source/BodyPartDictionary.cs

Reverted back to the previous method that we were using to find recipes for implants/bionics.

Fix for implant options

---

Source/CustomPawn.cs
Source/Page_ConfigureStartingPawnsCarefully.cs

Added a check when customizing apparel to make sure that the selected apparel has the ColorableComp.

Fix for apparel whose color cannot be customized

---

EdBPrepareCarefully.csproj
EdBPrepareCarefully.sln
Properties/AssemblyInfo.cs
Resources/About/About.xml
Resources/Languages/English/Keyed/EdBPrepareCarefully.xml
Source/DialogSelectParentChildPawn.cs
Source/DialogSelectPawn.cs
Source/Dialog_SaveColonist.cs
Source/Dialog_SavePreset.cs
Source/DragSlider.cs
Source/PanelAge.cs
Source/PanelEquipmentAvailable.cs
Source/PanelEquipmentSelected.cs
Source/PanelHealth.cs
Source/PanelName.cs
Source/PanelPawnList.cs
Source/State.cs
Source/WidgetNumberField.cs
Source/WidgetTable.cs

- Some translation fixes
- Fixed file overwrites for presets and colonists
- Added WidgetNumberField to allow users to type values into the numeric fields for age and equipment counts

Fixes for 0.17.0.3

---

Source/ExtensionsPawn.cs
Source/Injury.cs
Source/InjuryManager.cs
Source/Version3/PresetLoaderVersion3.cs
Source/Version3/SaveRecordInjuryV3.cs

Now storing pain factor with injuries so that the value does not randomly change for old injuries like scars.

Injury pain factor fixes

---

Resources/Languages/English/Keyed/EdBPrepareCarefully.xml
Source/PanelTraits.cs

- Added more conflict-checking when choosing traits so that you cannot stack traits that are not meant to be stacked.
- Tweaked the too-many-traits warning message.

Added trait conflict-checking

---

Resources/Languages/English/Keyed/EdBPrepareCarefully.xml
Source/ControllerPawns.cs
Source/PanelPawnList.cs
Source/ProviderFactions.cs

Added an "advanced add" button to the pawn list so that pawns from other factions can be added to the colony.

Advanced add button

---

Resources/About/About.xml
Resources/CHANGELOG.txt

- Incremented game version number to 0.17.1546
- Tweaked the change log notes

Incremented game version number to 0.17.1546

---

Source/AnimalDatabase.cs
Source/CostCalculator.cs
Source/EquipmentDatabase.cs
Source/PrepareCarefully.cs

Added better error-handling when adding equipment (especially animals) to the equipment database.

Equipment database error handling

---

Resources/Languages/English/Keyed/EdBPrepareCarefully.xml
Source/ControllerPawns.cs
Source/CustomPawn.cs
Source/PresetSaver.cs
Source/Version3/ColonistLoaderVersion3.cs
Source/Version3/PresetLoaderVersion3.cs
Source/Version3/SaveRecordPawnV3.cs
Source/Version3/SaveRecordRelationshipV3.cs

- Added better error-handling when saving and loading presets.
- Fixed problem where the CustomPawn id value was being set to null when loading pre-Alpha 17 characters.

Preset save fixes

---

Resources/Languages/English/Keyed/EdBPrepareCarefully.xml

Modified format of translation message change log.

Tweaked the header of the parent/child relationship panel

---

Resources/Languages/English/Keyed/EdBPrepareCarefully.xml
Source/Version3/ColonistLoaderVersion3.cs
Source/Version3/PresetLoaderVersion3.cs
Source/Version3/SaveRecordImplantV3.cs

- Tweaked error messages in preset loader
- Changed default saved part index from 0 to null for implants.

Preset loading tweaks

---

Resources/About/About.xml
Resources/CHANGELOG.txt

Updated game version to 0.17.1557

---

Resources/Languages/English/Keyed/EdBPrepareCarefully.xml
Source/PanelTraits.cs

Fixes for Issue #163:
- Updated trait previous/next buttons to take conflicting traits into account.
Also:
- Added the list of conflicting traits to the trait tooltip.

Fix for Issue #163

---

Source/EquipmentRecord.cs

Updated animal label in the selected equipment list to handle animals that have no gender.

Fix animal labels in selected equipment list

---

Source/CustomPawn.cs

Added fix when guessing which implant to add--no longer randomly chooses a matching implant from other alien races.

Implant initialization fix

---

Resources/CHANGELOG.txt
Source/CustomPawn.cs
Source/ProviderHealthOptions.cs

Added check to remove duplicate implant recipes if the recipe adds the same hediff on the same parts as another one.

Fix duplicate recipes

---

Libraries/README.md
README.md
Resources/CHANGELOG.txt

- Updated the READMEs with info about the new Harmony library.
- Updated change notes with info about using patches to add the button.

Updated READMEs with Harmony info

---

Resources/CHANGELOG.txt
Source/EquipmentDatabase.cs

Added a couple of additional null checks to the equipment database.

Equipment database null checks

---

Source/ExtensionsPawn.cs
Source/UtilityCopy.cs

- Reworked CopyExposable() to support constructor arguments so that it can be used to copy pawn tracker classes.
- Removed `UtilityCopy.CopyTrackerForPawn()`, replacing with calls to `UtilityCopy.CopyExposable<T>()`.
- Added `ExtensionsPawn.CopyModdedProperties()` to provide a single method where pawn properties from mods can be copied.
- Add `ExtensionsPawn.CopyExposableViaReflection()` to provide a way to copy an exposable via reflection (for copying classes introduced by mods).
- Added calls to copy two modded properties added by the Psychology mod.

Updated pawn copy methods to support modded pawn properties

---

Source/PanelRelationshipsParentChild.cs
Source/RelationshipManager.cs

Added ColonyPawns and HiddenPawns properties to RelationshipManager to centralize the logic for fetching these lists.  Updated the parent/child relationship panel to call these properties.

Added relationship manager properties to fetch pawn lists

---

Source/ControllerPawns.cs
Source/CustomPawn.cs
Source/Randomizer.cs

- Fixed the adult backstory randomizer

Fix for issue #195, issue #198 and issue #199

---

Source/CustomPawn.cs

Fix for issue #209.  Resetting skill XP progress whenever skill levels change.

Fix skill progress when changing skill levels

---

Source/ProviderAlienRaces.cs

Fixed field names in reflection lookups to match changes in the Alien Races mod.

Alien races mod fixes

---

Source/Page_PrepareCarefully.cs

Optimized the way that tabs are being rendered to avoid creating or iterating a new List every frame.

Tab rendering optimization

---

Source/Dialog_Options.cs

Optimized rendering of the contents of the options dialog so that it only draws options that are within the scrolling content area.

Options dialog rendering optimization

---

Source/AnimalRecord.cs
Source/Controller.cs
Source/ControllerPawns.cs
Source/CustomPawn.cs
Source/DialogManageImplants.cs
Source/DialogSelectParentChildPawn.cs
Source/Dialog_Colonist.cs
Source/Dialog_Preset.cs
Source/EquipmentRecord.cs
Source/FilterBackstorySkillAdjustment.cs
Source/Injury.cs
Source/Page_PrepareCarefully.cs
Source/PanelHealth.cs
Source/PanelIncapableOf.cs
Source/PanelPawnList.cs
Source/PanelRelationshipsOther.cs
Source/PanelRelationshipsParentChild.cs
Source/PanelSkills.cs
Source/PanelTraits.cs
Source/ProviderFactions.cs
Source/ProviderHealthOptions.cs
Source/ProviderPawnLayers.cs
Source/ScenPart_CustomAnimal.cs

Replaced deprecated calls to Translate(object[])

Replaced deprecated translation calls

---

Source/HarmonyPatches.cs

- Added better error handling and logging
- Now using Harmony AccessTools utility methods to get types (instead of typeof)

Tweaks to Harmony patches

---

Properties/AssemblyInfo.cs
Resources/About/About.xml
Resources/About/Manifest.xml
Source/Logger.cs
Source/OptionsHealth.cs
Source/ProviderAlienRaces.cs

- Fixed a bug where color swatches were not appearing when using the Humanoid Alien Races mod
- Fixed a bug where health options were not being sorted correctly.  This was being triggered by the Genetic Rim mod

Version 1.1.2 patch

---

Source/EquipmentDatabase.cs
Source/ManagerEquipment.cs
Source/PanelEquipmentAvailable.cs
Source/PresetLoaderV5.cs
Source/Version3/SaveRecordEquipmentV3.cs

category and random mechanoid from the available equipment panel when Biotech is not enabled.

Fixed loading mechanoids from saves. Removed mechanoid equipment
