Source/CustomPawn.cs
Added calls to clear the cache of disabled work types stored in `Pawn_StoryTracker`.  Cache needs to be cleared every time the backstories or traits are changed.
=> Issue #5: Fix for cached disabled work types

Source/Page_PrepareCarefully.cs
Fix for issue #7.   Uncommented the lines that reset the text alignment in `Page_PrepareCarefully`
=> Issue #7: Fixed text alignment when rendering point display

Source/ModController.cs
Fix for issue #6.  When mods are reloaded after making changes on the mod screen, textures need to be explicitly reloaded in the mod controller.
=> Issue #6: Added call to reset textures when mods are reloaded

Source/Page_ConfigureStartingPawnsCarefully.cs
=> Issue #17: Fixed backstory pre-selection when clicking on the adult backstory name

Resources/Languages/English/Keyed/EdBPrepareCarefully.xml, Source/CustomBodyPart.cs, Source/Injury.cs, Source/InjuryManager.cs, Source/Panel_Health.cs
Fixes to support scenario forced hediffs (i.e. cryptosleep sickness, malnutrition, etc).
- Renamed "injury" to "condition."
- Tweaked the logic that checks to see if a part must be selected for a hediff
- Other tweaks to support hediffs added to the whole body instead to a specific part.
=> Issue #4: Fixes to support scenario forced hediffs

Resources/Languages/English/Keyed/EdBPrepareCarefully.xml, Source/Page_ConfigureStartingPawns.cs, Source/PrepareCarefully.cs
Fix for issue #16.  Adding an alert when when Prepare Carefully cannot detect that its custom map generation step is available.
Cannot detect this 100% of time if additional map generators have been added (which is unlikely).
=> Issue #16: Added an alert when the prepare carefully genstep is not detected

Source/CustomPawn.cs, Source/Genstep_ScenParts.cs
Despite an earlier fix, there are still occasions where the disabled work categories for a pawn do no match up with customizations.  Added a couple of additional calls to clear the disabled work cache.
Also added code to reset the starting work priorities using the customized pawns.  This should fix the problem where the starting priorities did not seem to match the skills of the customized pawns.
=> Fixes to clear disabled work cache and reset starting work priorities

Source/Dialog_Options.cs, Source/InjuryManager.cs, Source/Panel_Health.cs
Adding enough injuries to kill a colonist throws an error, so we need to try to avoid it:
- Filtering out hediff stages that will definitely kill the colonist.
- Disabled certain injuries (non-"old injuries") in the injury dialog if you've already added them to the colonist (i.e. can no longer add malaria twice).
Also tweaked the spacing when drawing the disabled radio button texture.
=> Made it more difficult to kill a colonist by applying injuries

Source/CostCalculator.cs, Source/CustomPawn.cs, Source/Page_ConfigureStartingPawnsCarefully.cs, Source/Randomizer.cs, Source/Version3/PresetLoaderVersion3.cs, Source/Version3/SaveRecordPawnV3.cs
Refactored skill level code to fix various issues and to make it a little less confusing.
Should no longer get unexpected increases or decreases to skill levels when switch backstories and traits or when loading a new pawn.
Also tweaked the click region when clicking in the skill bar to set the value.  Feels a little more natural now.
=> Skill level refactor

Source/PrepareCarefully.cs
Added error checking to avoid trying to assign relationships between deleted pawns.
Saw this error happen after deleting a couple of pawns.  Not sure of the root cause, but the error handling should sidestep the problem.
=> Error checking when assignment custom relationships

Source/Genstep_ScenParts.cs
Cleaned up unneeded code for determining stack size and number of stacks when scattering resources near the colony starting position.  The `Genstep_ScatterThings` class takes care of this now.
=> Cleanup for resource scatterering code

Resources/Languages/English/Keyed/EdBPrepareCarefully.xml, Source/CustomPawn.cs, Source/Page_ConfigureStartingPawnsCarefully.cs, Source/PawnLayers.cs
- Added support for the Accessory layer
- Added the Personal Shield back into the apparel selections (had been explicitly removing it)
- Fixed the logic for determining apparel conflicts.  Should now allow apparel that covers the same layer but doesn't cover the same body part groups.
- Fixed the way that apparel is added to the finished pawn so that it now matches up with vanilla.  This fixes broken shield items.
=> Apparel enhancements

Source/ModController.cs
Fix for Issue #38.  Fixed the logic in `ModController.ModEnabled` to handle the case where multiple copies of the mod are installed.
=> Fixed ModController.ModEnabled to recognize multiple installs

Source/CustomPawn.cs
Added bounds-checking and null-pointer checks to avoid issues when getting the stuff color.
=> Better error-checking in CustomPawn.GetStuffColor

Source/Panel_Health.cs, Source/Version3/PresetLoaderVersion3.cs
- Removed debug logging statements from health panel
- Prevented presets from resetting the point value to the value saved with the preset.  It only made sense to do this before there were scenarios.
=> Tweaks/fixes for 0.14.2.1

Source/CustomPawn.cs
Bug fix for the display of disabled work types.  The CustomPawn constructor was not initializing this value.
=> Fixed issue with the initial display for "incapable of" work types

Source/GenStep_ScenParts.cs
- Fixed a logic flaw that could cause the mod to get stuck in an infinite loop while spawning items into the map.
- Changed the code to allow "made from stuff" items with no stuff to be spawned into the map with a default material.  Even though this pops up an error in development mode, it matches the vanilla behavior if you fail to assign a material to an item in a scenario.
=> Fix for issue #65: item spawn problem

Source/Randomizer.cs
Updated Randomizer.GenerateColonist() to explicitly use a PawnGenerationRequest with a few specific parameters in an attempt to better match the initial colonist generation.
Hopefully, by setting the pawn generation context value, we fix an issue where generated colonists were never getting assigned names from name-in-game pawns.
=> Pawn randomizer change

Resources/Languages/English/Keyed/EdBPrepareCarefully.xml, Source/Page_ConfigureStartingPawnsCarefully.cs, Source/Page_PrepareCarefully.cs, Source/PrepareCarefully.cs, Source/Textures.cs
- Changed the way that fatal errors are handled.  We now display a popup with the exception message to make it easier for users who are not familiar with development mode or logs files to post a screenshot of a problem.
- Added fix to re-initialize the mod textures whenever the Prepare Carefully window is opened.  This handles the case where textures are reset to null whenever you switch languages or enable/disable other mods without restarting.
=> Fixes for Issue #77

Source/CustomPawn.cs
- Added a call to clear the skill record cache after changing backstories.
- Changed the method to clear the cache to clear the list of all skill records in a pawn instead of just a single skill record to avoid multiple reflection lookups.
=> Bug fix for cached skill records

EdBPrepareCarefully.csproj, Source/BodyPartDictionary.cs, Source/CostCalculator.cs, Source/CustomPawn.cs, Source/HealthManager.cs, Source/ImplantManager.cs, Source/Panel_Health.cs, Source/Randomizer.cs, Source/Version3/PresetLoaderVersion3.cs, Source/Version3/SaveRecordPawnV3.cs
Better support for non-human pawns to try to prevent errors when playing with mods:
- Body parts and available implants are now computed based on the pawn's ThingDef.
- The pawn copying and randomizing code now duplicates the pawn using a matching PawnKindDef.
- The pawn's ThingDef is now saved with the preset.
=> Better support for modded non-human pawns

Source/CustomPawn.cs, Source/Page_ConfigureStartingPawnsCarefully.cs
- Added fix for screen blackout when selecting a pawn layer that has an RGB color slider (only a problem when using some other mods)
- Updated portrait cache clearing to only clear the cache once per frame.
- Removed some unused/commented-out code.
=> Screen blackout fix

Source/Version3/PresetLoaderVersion3.cs, Source/Version3/SaveRecordPawnV3.cs
Added PawnKindDef to the preset save file and changed the way that presets are loaded to generate a colonist using the saved kind def, if available.
=> Add PawnKindDef to saved presets

EdBPrepareCarefully.csproj, EdBPrepareCarefully.sln, Properties/AssemblyInfo.cs, Resources/About/About.xml, Resources/Languages/English/Keyed/EdBPrepareCarefully.xml, Source/CostCalculator.cs, Source/CustomPawn.cs, Source/GenStep_ScenParts.cs, Source/PanelTraits.cs, Source/Version3/ColonistLoaderVersion3.cs, Source/Version3/PresetLoaderVersion3.cs, Source/Version3/SaveRecordPawnV3.cs
- Fixed issues with loading old presets
- Added null pointer check for the new "otherPawns" section (missing from older presets)
- Added replacement logic for the renamed survival rifle thingDef.
- Fixed issued where the pawn's appearance did not properly reflect whether or not they are downed.
- Re-applying hediffs and clearing caches when changing traits and adding health conditions
- Removed redundant code that re-applies hediffs right before spawning colonists into the map.
=> Fixes for loading pre-Alpha 17 presets and fixes for downed colonists

Resources/Languages/English/Keyed/EdBPrepareCarefully.xml, Source/Controller.cs, Source/GenStep_CustomScatterThings.cs, Source/Page_PrepareCarefully.cs, Source/PanelIncapableOf.cs, Source/PanelPawnList.cs, Source/State.cs
Added a warning to the IncapableOf panel to warn the user if their pawns are all missing work types that are considered required.  Adding the alert so that the user knows what happened when they get the subsequent error when the map generates.
=> Missing work types warning

Source/CustomPawn.cs, Source/DialogSelectParentChildPawn.cs, Source/PanelRelationshipsOther.cs, Source/PanelRelationshipsParentChild.cs
- Split the `CustomPawn.ProfessionLabel` property into long and short versions, `ProfessionLabel` and `ProfessionLabelShort`
- Changed the relationship pawn tooltip to use the long profession instead of the short one.
=> Changes to profession label

Resources/Languages/English/Keyed/EdBPrepareCarefully.xml, Source/Constraints.cs, Source/CostCalculator.cs, Source/CustomPawn.cs, Source/PanelBase.cs, Source/PanelIncapableOf.cs, Source/PanelTraits.cs
- Added an alert/warning for when the user adds more than three traits to a character.
- Changed the visual treatment of the alert in the "Incapable Of" panel to match the new one in the "Traits" panel.
- Cost calculator changes for more than four traits.
=> Added warning for more than three traits

Source/Dialog_Options.cs, Source/PanelHealth.cs, Source/PanelPawnList.cs, Source/PanelRelationshipsOther.cs, Source/PanelTraits.cs
Updated the options dialog to expect aleady-translated text for header and button labels.
=> Expect translated text in the options dialog

Source/BodyPartDictionary.cs, Source/ControllerPawns.cs, Source/CustomPawn.cs, Source/ImplantManager.cs, Source/InjuryManager.cs, Source/PrepareCarefully.cs
- Moved pawn hediff initialization code from InjuryManager into CustomPawn.
- Added implant initialization code for new pawns.
Also:
- Includes fix so that passions are not assigned to disabled skills.
- Includes fix so that random pawn kind selection for faction pawns does not exclude factions whose names are not unique (i.e. Spacers)
=> Refactor injury/implant initialization for new pawns

EdBPrepareCarefully.csproj, EdBPrepareCarefully.sln, Resources/About/About.xml, Source/ControllerPawns.cs, Source/CustomParentChildPawn.cs, Source/CustomPawn.cs, Source/PanelAppearance.cs, Source/PanelRelationshipsParentChild.cs, Source/ProviderHeadType.cs, Source/RaceHeadTypes.cs, Source/Version3/ColonistLoaderVersion3.cs
- Incremented version number to 0.17.1.1.
- Started support for alien races framework compatibility by splitting out the head type provider to support a separate set of head types per race.
- Doesn't actually work yet, but it's a step forward.
- Disabling head type selection for pawns that have unrecognized head graphics.
- Fixed problem where the name was visible for hidden pawns in a tooltip in the relationships tab view.
- Sorted apparel materials almost alphabetically.
- Assigning a new ID to a loaded character if its ID conflicts with that of another pawn.
=> Bugfixes for 0.17.1.1

Source/ControllerPawns.cs, Source/CustomPawn.cs, Source/PanelPawnList.cs, Source/PrepareCarefully.cs, Source/ProviderFactions.cs, Source/Providers.cs, Source/Randomizer.cs, Source/Version3/SaveRecordPawnV3.cs
Various fixes for faction pawns:
- Centralized dummy faction creation in the faction provider.
- A pawn's faction is now properly maintained when clicking the randomize buttons.
- Better approach to filtering out pawn kinds that cannot be created.
- Implemented a workaround to prevent weapons from being generated with a faction pawn.
- Changed pawn generation context from "non-player" to "player start" in all cases.
Also:
- Moved some functions from `Randomizer` into `ControllerPawns`
- Renamed and reworked some pawn generation `Randomizer` methods
- Added a `CustomPawn.LastSelectedAdulthoodBackstory` property whose getter randomly chooses a backstory if the underlying fields value is null--no longer randomly choosing a value during construction.
=> Faction pawn fixes

EdBPrepareCarefully.csproj, Resources/CHANGELOG.txt, Source/PresetSaver.cs, Source/RelationshipManager.cs, Source/Version3/PresetLoaderVersion3.cs, Source/Version3/SaveRecordParentChildGroupV3.cs
- Updated the preset file format to explicitly include parent/child groups (so that sibling-only groups are not lost on save).
- Reworked how the preset loader interacts with the RelationshipManager class.
=> Preset fix for sibling-only relationships

Source/RelationshipBuilder.cs
Updated sibling-only relationships to create both parents to avoid the game assuming them to be half-siblings.
=> Fix for sibling relationships

Source/RelationshipBuilder.cs
Fixed the way that hidden pawns are spawned into the world so that pawns that are already spawned will not be killed.
=> Hidden pawn world spawn fix

Resources/CHANGELOG.txt, Source/ControllerPawns.cs, Source/ProviderFactions.cs
- Can now choose from both player and non-player factions when creating a new faction pawn.
- "Randomize All" now chooses between all of the available pawn kinds for the pawn's faction when generating the new random pawn.
=> Player faction pawn changes

Resources/CHANGELOG.txt, Source/CustomBodyPart.cs, Source/CustomPawn.cs, Source/Implant.cs, Source/PanelHealth.cs, Source/ScrollViewVertical.cs
- No longer treating all implants as replaced parts, which was causing implant locations to be disabled in some cases when they should not have been.
- Also tweaked the way that scroll views evaluate the `scrollTo` location.
=> Fix disabled implant locations

Source/ControllerPawns.cs, Source/CustomPawn.cs, Source/PanelName.cs, Source/PrepareCarefully.cs
- Removed the faction from all pawns while they are being prepared. This avoids a bug in the info health panel related to self-doctoring.
- The faction is now set when preparing pawns for spawn.
=> Removed faction value from pawns

Resources/Defs/CarefullyPawnRelationDefs/CarefullyPawnRelations_FamilyByChoice.xml, Source/CarefullyPawnRelationDef.cs, Source/RelationshipBuilder.cs
- Added field to CarefullyPawnRelationDef to indicate whether or not a relationship should try to find more compatible pawns.
- Updated relationship builder to reassign pawn ThingIds to try to end up with more compatible pawns.
=> Pawn relationship compatibility fixes

Source/CustomPawn.cs
Reverted the change that set the pawn's faction to null while Prepare Carefully.  Doing so avoided an exception in the health info tab in some cases, but it also breaks compatibility with the Facial Stuff mod.  Will live with the health tab bug until we can find another approach.
=> Revert null faction workaround

EdBPrepareCarefully.csproj, Source/ProviderAlienRaces.cs, Source/ProviderHair.cs
Basically this was in issue in two parts.
One:
The results to grab the hair colors would return the skin colors instead of the hair swatches.
Two:
There was no check that applied the hair swatches unless there was no custom set hair.
=> Fixed Alien Races hair color swatches not showing up.

Properties/AssemblyInfo.cs, Resources/About/About.xml, Resources/About/Manifest.xml, Source/AlienRace.cs, Source/PanelAppearance.cs, Source/PanelEquipmentAvailable.cs, Source/ProviderAlienRaces.cs, Source/Randomizer.cs, Source/Version4/SaveRecordPawnV4.cs
- Fixed problems with sorting `TaggedString`s.  We need to call `Resolve()` on them before passing them as an argument to a `Compare()` method
- Fixed a null-pointer caused by Alien Race definitions that have a null `ColorGenerator`  
- Changed `Randomizer.RandomAdulthood()` to choose a random backstory from a list provided by `ProviderBackstories`.
- The previous implementation was returning `null` instead of a valid backstory
- This was causing a null-pointer exception when saving a preset because `CustomPawn.LastSelectedAdultBackstory` would unexpectedly return `null`.  We added a null-pointer check in the preset saving code
=> Version 1.1.3

EdBPrepareCarefully.csproj, Properties/AssemblyInfo.cs, Resources/About/About.xml, Resources/About/Manifest.xml, Resources/CHANGELOG.txt, Source/ControllerPawns.cs, Source/ExtensionsPawn.cs, Source/PawnBioGenerator.cs, Source/Reflection.cs, Source/ReflectionCache.cs
- Bug fixes
- Fixed an issue when adding faction pawns from the Shattered Empire.
- Compatibility fix with Vanilla Hair Expanded.
- Fixed an issue with the randomize backstories button when the Alien Races mod is enabled.
- Updated the Pawn copying code to automatically copy `ThingComps` instead of explicitly copying only the comps that we know about.  This _may_ introduce problems with some mods but seems to help more than it hurts for now.
=> Version 1.1.4
